### PR TITLE
Added colors to console-printed messages.

### PR DESCRIPTION
**Pull request by TheOdd**

### CODE REVIEW

**Comment by ghost** [comment]
Please use rebasing instead of merges

**Comment by TheOdd** [comment]
@nvllvs Can I PM you in Gitter or something because I'd love to, but GitHub is so damn irritating and I'm not sure how to.

**Comment by brcly** [comment]
It's not a big deal @nvllvs we can just squash any merges.

I'd prefer a better system tho.

**Comment by TheOdd** [comment]
@AnterGhost I'm quite new to this, so I'm going to try to make it cleaner. It's been bothering me anyways.

**Comment by brcly** [comment]
I've added a basic implementation.

Feel free to improve it.

**Pull request closed without merging**
